# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calculadora_Coordenadas
                                 A QGIS plugin
 convertidor de coordenadas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-03
        copyright            : (C) 2023 by Fatima Matamoros
        email                : fatimamatamoros1315@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Calculadora_Coordenadas class from file Calculadora_Coordenadas.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Cal_coor import Calculadora_Coordenadas
    return Calculadora_Coordenadas(iface)
